replicaCount: 1

image:
  imagerepo: docker.io/kubewatch/kubewatch 
  imagetag: latest 
  pullPolicy: Always
# to enable debug logging
debug: false

kubewatchRole:
  enabled: true
  rules:
  - apiGroups:
      - ""
    resources:
      - "*" 
    verbs:
      - list
      - read  
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
  - apiGroups:
      - "policy"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
