apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubewatch
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubewatch 
    app.kubernetes.io/part-of: kubewatch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubewatch-clusterrole
  labels:
    app.kubernetes.io/name: kubewatch
    app.kubernetes.io/part-of: kubewatch
rules:
  - apiGroups:
      - ""
    resources:
      - "*" 
    verbs:
      - list
      - read  
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch
  - apiGroups:
      - "policy"
    resources:
      - "*"
    verbs:
      - list
      - read
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubewatch-binding
  labels:
    app.kubernetes.io/name: kubewatch
    app.kubernetes.io/part-of: kubewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewatch-clusterrole
subjects:
  - kind: ServiceAccount
    name: kubewatch
    namespace: kube-system


